### ISSUE TITLE
option to use as a toggle

### ISSUE THREAD

**Issue by angelotc** [DIYCharles/MouseJiggler#2]
For those of us with regular keyboards, and we are trying to implement this code it does it every time the keycode is hit. Which means I have to hold it down. Would be nice if there was a way to give it an option as a toggle!

**Comment by DIYCharles** [comment]
Ok I will work on that soon. It will just be a function that a macro will set a Boolean to true or false. I'll have the code to you soon.

**Comment by DIYCharles** [comment]
@angelotc Check in my newest commit. Let me know if you have anymore questions. Please close the issue if it all works for you. 

[New Commit](https://github.com/DIYCharles/MouseJiggler/commit/1c6ffce0e4f2baf05b926ecd3765f9f1ecf66428)
 @angelotc 

[yeet](https://github.com/DIYCharles/MouseJiggler/commit/1c6ffce0e4f2baf05b926ecd3765f9f1ecf66428)
https://github.com/DIYCharles/MouseJiggler/commit/1c6ffce0e4f2baf05b926ecd3765f9f1ecf66428

I also added a section in the readme talking about it.
